name: allow-merge

on:
  push:
    
  workflow_dispatch:
    inputs:
      pr: {required: true}
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: [ "ubuntu-latest"]
    steps:
      - name: Step-01
        run: |
          Echo "I'm Action Action-01"