name: allow-merge

on:
  workflow_dispatch:
    inputs:
      pr: {required: true}
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
#    if: github.repository == 'dyazgi/HarmonieCSC'
    runs-on: [ "ubuntu-latest"]
    steps:
      - name: Step-01
        run: |
          Echo "I'm Action Action-01"