name: allow-merge

on:    
  workflow_dispatch:
    inputs:
      pr: {required: true}
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  allow-merge-job:
    runs-on: [ "ubuntu-latest"]
    steps:
      - name: allow-merge-step-01
        run: |
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Job ID (env): $GITHUB_JOB"
          echo "Job ID (context): ${{ github.job }}"
          exit 0