name: on-push
on:
  push:
    paths:
      - .github/workflows/on-push.yaml

jobs:
  on-push-job:
    runs-on: ubuntu-latest
    steps:
      - name: on-push-step-01
        run: |
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Job ID (env): $GITHUB_JOB"
          echo "Job ID (context): ${{ github.job }}"